//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWichData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Trainings = new HashSet<Training>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Event_Content { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Rating { get; set; }
        public Nullable<int> Trainer_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Booking { get; set; }
        public Nullable<int> Assigned { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
