//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWichData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Events = new HashSet<Event>();
            this.Trainings = new HashSet<Training>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Event_ID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual Event Event { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
