//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWichData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int ID { get; set; }
        public Nullable<int> Staff_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Session_ID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Session Session { get; set; }
    }
}
