//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWichData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public Trainer()
        {
            this.Events = new HashSet<Event>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Event_ID { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual Event Event { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
